import type { OxlintConfig } from 'oxlint';

const config = {
	jsPlugins: [
		{
			name: '@neon/eslint-react',
			specifier: 'eslint-plugin-react',
		},
		{
			name: '@neon/eslint-stylistic',
			specifier: '@stylistic/eslint-plugin',
		},
		{
			name: '@neon/eslint-unicorn',
			specifier: 'eslint-plugin-unicorn',
		},
		{
			name: '@neon/eslint-vue',
			specifier: 'eslint-plugin-vue',
		},
	],
	overrides: [
		{
			files: ['**/*.{js,jsx,ts,tsx,cjs,mjs,cts,mts}'],
			rules: {
				'@neon/eslint-react/jsx-child-element-spacing': 'off',
				'@neon/eslint-react/jsx-closing-bracket-location': 'off',
				'@neon/eslint-react/jsx-closing-tag-location': 'off',
				'@neon/eslint-react/jsx-curly-newline': 'off',
				'@neon/eslint-react/jsx-curly-spacing': 'off',
				'@neon/eslint-react/jsx-equals-spacing': 'off',
				'@neon/eslint-react/jsx-first-prop-new-line': 'off',
				'@neon/eslint-react/jsx-indent': 'off',
				'@neon/eslint-react/jsx-indent-props': 'off',
				'@neon/eslint-react/jsx-max-props-per-line': 'off',
				'@neon/eslint-react/jsx-newline': 'off',
				'@neon/eslint-react/jsx-one-expression-per-line': 'off',
				'@neon/eslint-react/jsx-props-no-multi-spaces': 'off',
				'@neon/eslint-react/jsx-space-before-closing': 'off',
				'@neon/eslint-react/jsx-tag-spacing': 'off',
				'@neon/eslint-react/jsx-wrap-multilines': 'off',
				'@neon/eslint-stylistic/array-bracket-newline': 'off',
				'@neon/eslint-stylistic/array-bracket-spacing': 'off',
				'@neon/eslint-stylistic/array-element-newline': 'off',
				'@neon/eslint-stylistic/arrow-parens': 'off',
				'@neon/eslint-stylistic/arrow-spacing': 'off',
				'@neon/eslint-stylistic/block-spacing': 'off',
				'@neon/eslint-stylistic/brace-style': 'off',
				'@neon/eslint-stylistic/comma-dangle': 'off',
				'@neon/eslint-stylistic/comma-spacing': 'off',
				'@neon/eslint-stylistic/comma-style': 'off',
				'@neon/eslint-stylistic/computed-property-spacing': 'off',
				'@neon/eslint-stylistic/dot-location': 'off',
				'@neon/eslint-stylistic/eol-last': 'off',
				'@neon/eslint-stylistic/function-call-spacing': 'off',
				'@neon/eslint-stylistic/function-call-argument-newline': 'off',
				'@neon/eslint-stylistic/function-paren-newline': 'off',
				'@neon/eslint-stylistic/generator-star-spacing': 'off',
				'@neon/eslint-stylistic/implicit-arrow-linebreak': 'off',
				'@neon/eslint-stylistic/indent': 'off',
				'@neon/eslint-stylistic/indent-binary-ops': 'off',
				'@neon/eslint-stylistic/jsx-quotes': 'off',
				'@neon/eslint-stylistic/key-spacing': 'off',
				'@neon/eslint-stylistic/keyword-spacing': 'off',
				'@neon/eslint-stylistic/linebreak-style': 'off',
				'@neon/eslint-stylistic/lines-around-comment': 0,
				'@neon/eslint-stylistic/max-len': 0,
				'@neon/eslint-stylistic/max-statements-per-line': 'off',
				'@neon/eslint-stylistic/multiline-ternary': 'off',
				'@neon/eslint-stylistic/new-parens': 'off',
				'@neon/eslint-stylistic/newline-per-chained-call': 'off',
				'@neon/eslint-stylistic/no-confusing-arrow': 0,
				'@neon/eslint-stylistic/no-extra-parens': 'off',
				'@neon/eslint-stylistic/no-extra-semi': 'off',
				'@neon/eslint-stylistic/no-floating-decimal': 'off',
				'@neon/eslint-stylistic/no-mixed-operators': 0,
				'@neon/eslint-stylistic/no-mixed-spaces-and-tabs': 'off',
				'@neon/eslint-stylistic/no-multi-spaces': 'off',
				'@neon/eslint-stylistic/no-multiple-empty-lines': 'off',
				'@neon/eslint-stylistic/no-tabs': 0,
				'@neon/eslint-stylistic/no-trailing-spaces': 'off',
				'@neon/eslint-stylistic/no-whitespace-before-property': 'off',
				'@neon/eslint-stylistic/nonblock-statement-body-position': 'off',
				'@neon/eslint-stylistic/object-curly-newline': 'off',
				'@neon/eslint-stylistic/object-curly-spacing': 'off',
				'@neon/eslint-stylistic/object-property-newline': 'off',
				'@neon/eslint-stylistic/one-var-declaration-per-line': 'off',
				'@neon/eslint-stylistic/operator-linebreak': 'off',
				'@neon/eslint-stylistic/padded-blocks': 'off',
				'@neon/eslint-stylistic/quote-props': 'off',
				'@neon/eslint-stylistic/quotes': 0,
				'@neon/eslint-stylistic/rest-spread-spacing': 'off',
				'@neon/eslint-stylistic/semi': 'off',
				'@neon/eslint-stylistic/semi-spacing': 'off',
				'@neon/eslint-stylistic/semi-style': 'off',
				'@neon/eslint-stylistic/space-before-blocks': 'off',
				'@neon/eslint-stylistic/space-before-function-paren': 'off',
				'@neon/eslint-stylistic/space-in-parens': 'off',
				'@neon/eslint-stylistic/space-infix-ops': 'off',
				'@neon/eslint-stylistic/space-unary-ops': 'off',
				'@neon/eslint-stylistic/switch-colon-spacing': 'off',
				'@neon/eslint-stylistic/template-curly-spacing': 'off',
				'@neon/eslint-stylistic/template-tag-spacing': 'off',
				'@neon/eslint-stylistic/wrap-iife': 'off',
				'@neon/eslint-stylistic/wrap-regex': 'off',
				'@neon/eslint-stylistic/yield-star-spacing': 'off',
				'@neon/eslint-stylistic/jsx-child-element-spacing': 'off',
				'@neon/eslint-stylistic/jsx-closing-bracket-location': 'off',
				'@neon/eslint-stylistic/jsx-closing-tag-location': 'off',
				'@neon/eslint-stylistic/jsx-curly-newline': 'off',
				'@neon/eslint-stylistic/jsx-curly-spacing': 'off',
				'@neon/eslint-stylistic/jsx-equals-spacing': 'off',
				'@neon/eslint-stylistic/jsx-first-prop-new-line': 'off',
				'@neon/eslint-stylistic/jsx-indent': 'off',
				'@neon/eslint-stylistic/jsx-indent-props': 'off',
				'@neon/eslint-stylistic/jsx-max-props-per-line': 'off',
				'@neon/eslint-stylistic/jsx-newline': 0,
				'@neon/eslint-stylistic/jsx-one-expression-per-line': 0,
				'@neon/eslint-stylistic/jsx-props-no-multi-spaces': 0,
				'@neon/eslint-stylistic/jsx-tag-spacing': 0,
				'@neon/eslint-stylistic/jsx-wrap-multilines': 0,
				'@neon/eslint-stylistic/line-comment-position': 0,
				'@neon/eslint-stylistic/member-delimiter-style': 'off',
				'@neon/eslint-stylistic/type-annotation-spacing': 'off',
				'@neon/eslint-stylistic/type-generic-spacing': 'off',
				'@neon/eslint-stylistic/type-named-tuple-spacing': 'off',
				'@neon/eslint-unicorn/template-indent': 0,
			},
		},
		{
			files: ['**/*.vue'],
			rules: {
				'@neon/eslint-vue/array-bracket-newline': 'off',
				'@neon/eslint-vue/array-bracket-spacing': 'off',
				'@neon/eslint-vue/array-element-newline': 'off',
				'@neon/eslint-vue/arrow-spacing': 'off',
				'@neon/eslint-vue/block-spacing': 'off',
				'@neon/eslint-vue/block-tag-newline': 'off',
				'@neon/eslint-vue/brace-style': 'off',
				'@neon/eslint-vue/comma-dangle': 'off',
				'@neon/eslint-vue/comma-spacing': 'off',
				'@neon/eslint-vue/comma-style': 'off',
				'@neon/eslint-vue/dot-location': 'off',
				'@neon/eslint-vue/func-call-spacing': 'off',
				'@neon/eslint-vue/html-closing-bracket-newline': 'off',
				'@neon/eslint-vue/html-closing-bracket-spacing': 'off',
				'@neon/eslint-vue/html-end-tags': 'off',
				'@neon/eslint-vue/html-indent': 'off',
				'@neon/eslint-vue/html-quotes': 'off',
				'@neon/eslint-vue/html-self-closing': 0,
				'@neon/eslint-vue/key-spacing': 'off',
				'@neon/eslint-vue/keyword-spacing': 'off',
				'@neon/eslint-vue/max-attributes-per-line': 'off',
				'@neon/eslint-vue/max-len': 0,
				'@neon/eslint-vue/multiline-html-element-content-newline': 'off',
				'@neon/eslint-vue/multiline-ternary': 'off',
				'@neon/eslint-vue/mustache-interpolation-spacing': 'off',
				'@neon/eslint-vue/no-extra-parens': 'off',
				'@neon/eslint-vue/no-multi-spaces': 'off',
				'@neon/eslint-vue/no-spaces-around-equal-signs-in-attribute': 'off',
				'@neon/eslint-vue/object-curly-newline': 'off',
				'@neon/eslint-vue/object-curly-spacing': 'off',
				'@neon/eslint-vue/object-property-newline': 'off',
				'@neon/eslint-vue/operator-linebreak': 'off',
				'@neon/eslint-vue/quote-props': 'off',
				'@neon/eslint-vue/script-indent': 'off',
				'@neon/eslint-vue/singleline-html-element-content-newline': 'off',
				'@neon/eslint-vue/space-in-parens': 'off',
				'@neon/eslint-vue/space-infix-ops': 'off',
				'@neon/eslint-vue/space-unary-ops': 'off',
				'@neon/eslint-vue/template-curly-spacing': 'off',
			},
		},
	],
	rules: {},
	plugins: [],
} satisfies OxlintConfig;

export default config;
